"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class controller_t(object):
    __slots__ = ["timestamp", "control", "error_code", "enabled"]

    __typenames__ = ["int64_t", "double", "int16_t", "boolean"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.control = 0.0
        self.error_code = 0
        self.enabled = False

    def encode(self):
        buf = BytesIO()
        buf.write(controller_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdhb", self.timestamp, self.control, self.error_code, self.enabled))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != controller_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return controller_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = controller_t()
        self.timestamp, self.control, self.error_code = struct.unpack(">qdh", buf.read(18))
        self.enabled = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if controller_t in parents: return 0
        tmphash = (0xf23445fc96d54959) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if controller_t._packed_fingerprint is None:
            controller_t._packed_fingerprint = struct.pack(">Q", controller_t._get_hash_recursive([]))
        return controller_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", controller_t._get_packed_fingerprint())[0]

