"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class plant_t(object):
    __slots__ = ["timestamp", "state", "error_code", "enabled"]

    __typenames__ = ["int64_t", "double", "int16_t", "boolean"]

    __dimensions__ = [None, [2], None, None]

    def __init__(self):
        self.timestamp = 0
        self.state = [ 0.0 for dim0 in range(2) ]
        self.error_code = 0
        self.enabled = False

    def encode(self):
        buf = BytesIO()
        buf.write(plant_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>2d', *self.state[:2]))
        buf.write(struct.pack(">hb", self.error_code, self.enabled))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != plant_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return plant_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = plant_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.state = struct.unpack('>2d', buf.read(16))
        self.error_code = struct.unpack(">h", buf.read(2))[0]
        self.enabled = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if plant_t in parents: return 0
        tmphash = (0x2aa2867ba85501ca) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if plant_t._packed_fingerprint is None:
            plant_t._packed_fingerprint = struct.pack(">Q", plant_t._get_hash_recursive([]))
        return plant_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", plant_t._get_packed_fingerprint())[0]

